In [203]:
import re
import numpy as np
from scipy import spatial

In [204]:
file = open('sentences.txt', 'r+')

In [205]:
sentence_list = file.readlines()

In [206]:
sentence_list_lower = []
for i in sentence_list:
    sentence_list_lower.append(i.lower())
    

In [207]:
print(sentence_list_lower)

['in comparison to dogs, cats have not undergone major changes during the domestication process.\n', 'as cat simply catenates streams of bytes, it can be also used to concatenate binary files, where it will just concatenate sequence of bytes.\n', 'a common interactive use of cat for a single file is to output the content of a file to standard output.\n', 'cats can hear sounds too faint or too high in frequency for human ears, such as those made by mice and other small animals.\n', 'in one, people deliberately tamed cats in a process of artificial selection, as they were useful predators of vermin.\n', 'the domesticated cat and its closest wild ancestor are both diploid organisms that possess 38 chromosomes and roughly 20,000 genes.\n', 'domestic cats are similar in size to the other members of the genus felis, typically weighing between 4 and 5 kg (8.8 and 11.0 lb).\n', 'however, if the output is piped or redirected, cat is unnecessary.\n', 'cat with one named file is safer where human

In [208]:
n = 0
sentence = []
for line in sentence_list_lower:
    #print(n)
    #print(len(sentence_list_lower))
    #print(line)
    #word = list(filter(None, re.split('[^a-z]', line))
    word = re.split('[^a-z]', line)
    word = list(filter(bool, word))
    sentence.append(word)
    n = n + 1
    

In [209]:
print(sentence)

[['in', 'comparison', 'to', 'dogs', 'cats', 'have', 'not', 'undergone', 'major', 'changes', 'during', 'the', 'domestication', 'process'], ['as', 'cat', 'simply', 'catenates', 'streams', 'of', 'bytes', 'it', 'can', 'be', 'also', 'used', 'to', 'concatenate', 'binary', 'files', 'where', 'it', 'will', 'just', 'concatenate', 'sequence', 'of', 'bytes'], ['a', 'common', 'interactive', 'use', 'of', 'cat', 'for', 'a', 'single', 'file', 'is', 'to', 'output', 'the', 'content', 'of', 'a', 'file', 'to', 'standard', 'output'], ['cats', 'can', 'hear', 'sounds', 'too', 'faint', 'or', 'too', 'high', 'in', 'frequency', 'for', 'human', 'ears', 'such', 'as', 'those', 'made', 'by', 'mice', 'and', 'other', 'small', 'animals'], ['in', 'one', 'people', 'deliberately', 'tamed', 'cats', 'in', 'a', 'process', 'of', 'artificial', 'selection', 'as', 'they', 'were', 'useful', 'predators', 'of', 'vermin'], ['the', 'domesticated', 'cat', 'and', 'its', 'closest', 'wild', 'ancestor', 'are', 'both', 'diploid', 'organism

In [210]:
word_dict = []
for i, word in enumerate(sentence):
    for word1 in sentence[i]:
        word_dict.append(word1)
        
set_word_dict = list(set(word_dict))
print(len(set_word_dict))
print(set_word_dict)

254
['features', 'piped', 'developed', 'undergone', 'made', 'needing', 'later', 'hear', 'right', 'stdin', 'in', 'similar', 'versions', 'osx', 'deliberately', 'installed', 'artificial', 'if', 'second', 'place', 'off', 'most', 'for', 'patch', 'purchase', 'possess', 'time', 'legibility', 'domestic', 'such', 'were', 'need', 'bytes', 'domesticated', 'starting', 'mavericks', 't', 'release', 'animals', 'editions', 'yosemite', 'drive', 'keyboards', 'to', 'so', 'streams', 'just', 'allow', 'non', 'frequency', 'app', 'redirected', 'moved', 'an', 'allows', 'run', 'read', 'world', 'every', 'sequence', 'binary', 'high', 'based', 'are', 'unnecessary', 'october', 'recent', 'catenates', 'between', 'x', 'symbol', 'symbols', 'dogs', 'terms', 'releasing', 'by', 'won', 'one', 'marks', 'it', 'separate', 'fifth', 'selection', 'pipes', 'cat', 'according', 'small', 'with', 'displays', 'now', 'community', 'not', 'adjacent', 'predators', 'wrong', 'diploid', 'connected', 'which', 'releases', 'of', 'will', 'they',

In [211]:
n = len(sentence)
d = len(set_word_dict)
A = np.ones(shape=(n, d))
print(A)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [212]:
mean_for_matrix = [[]]
for i, word in enumerate(sentence):
    for z, k in enumerate(set_word_dict):
        test = word.count(k)
        A[(i, z)] = test
print(A[0, 11])



0.0


In [213]:
dists = []
for row in A:
    dists.append(scipy.spatial.distance.cosine(A[0,:], row))

In [215]:
for n, i in enumerate(dists):
    print(n+1, ' : ', i)

1  :  0.0
2  :  0.9527544408738466
3  :  0.8644738145642124
4  :  0.8951715163278082
5  :  0.7770887149698589
6  :  0.9402385695332803
7  :  0.7327387580875756
8  :  0.9258750683338899
9  :  0.8842724875284311
10  :  0.9055088817476932
11  :  0.8328165362273942
12  :  0.8804771390665607
13  :  0.8396432548525454
14  :  0.8703592552895671
15  :  0.8740118423302576
16  :  0.9442721787424647
17  :  0.8406361854220809
18  :  0.956644501523794
19  :  0.9442721787424647
20  :  0.8885443574849294
21  :  0.8427572744917122
22  :  0.8250364469440588


# Conclusion

Here I decided one problem: 
I compare all sentences in text with first(indec = 0).
Here I used algothim of cosin from scipy lib.
I found two simiar sentences fith first one. 
Their numbers are : 5 and 7